# Generated by Django 5.2.2 on 2025-06-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_historial_iteraciones_historial_pasos_historial_x0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
