# Generated by Django 5.2.2 on 2025-07-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='metodo_tipo',
            field=models.CharField(choices=[('Numerico', 'Método Numérico'), ('Simplex', 'Método Simplex')], default='Numerico', max_length=20),
        ),
        migrations.AddField(
            model_name='historial',
            name='parametros_simplex',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='iteraciones',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='pasos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='x0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='x1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='x2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
